[package]
name = "cinny-desktop"
version = "4.11.2"
description = "星火桌面客户端"
authors = ["Cinny contributors"]
license = "AGPL-3.0-only"
edition = "2021"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = [] }
tauri-plugin-process = "2"
tauri-plugin-updater = "2"
